### ISSUE TITLE
Compare from only part of image (using x, y coordinate)

### ISSUE THREAD

**Issue by JhonImmanuel** [Huddle/Resemble.js#100]
Sometimes we just wanted to know what difference in some part of image, is it your API support for compare just a part of image and not a whole image file?

Maybe sent X, Y coordinate.

Thanks.

**Comment by jamescryer** [comment]
Good feature request, I'd be happy to review and accept a Pull Request

**Comment by AnnasLab** [comment]
Following

**Comment by jamescryer** [comment]
I believe the https://github.com/Huddle/Resemble.js/pull/103 resolves this ticket.  Thanks all.
