### ISSUE TITLE
Compare Image from URL

### ISSUE THREAD

**Issue by thyash11** [Huddle/Resemble.js#102]
Hi,

I would like to know, how can I compare two images by url.

for that I have written this below line and compared.
var restr = new File([""], "http://localhost/res/demoassets/People.jpg");
var restt = new File([""], "http://localhost/res/demoassets/People2.jpg");
resemble(restr).compareTo(restt).onComplete(onComplete)

but it is showing error like below.
GET data: net::ERR_INVALID_URL.

It would be a great help!!! Thanks!!!

**Comment by jamescryer** [comment]
This should work in the browser. `resemble('http://localhost/res/demoassets/People.jpg').compareTo('http://localhost/res/demoassets/People2.jpg').onComplete(onComplete)`

See example at bottom of https://github.com/Huddle/Resemble.js/blob/master/demoassets/main.js

**Comment by thyash11** [comment]
Thank You jamescryer,

I was so dumb. I figured it from the same file after few hours.
