### ISSUE TITLE
Windows npm install fails after bugfix release

### ISSUE THREAD

**Issue by rogierschouten** [Huddle/Resemble.js#107]
Hi,

After your commit b1ddc451e30be835aec94fb26ecf323da51bec51 and resulting release 2.2.5, NPM install starts to fail with a missing peer dependency 'canvas'.  This canvas module however cannot be just installed using NPM on windows. It requires extra installation steps on our development and build machines, which is really undesirable.

I think this should not have occurred in a bugfix release since it's clearly backwards incompatible. But is this dependency really necessary at all? Can it be removed or replaced with a windows-compatible module? Why is it a peer dependency and not a normal one? I'm confused.

**Comment by jamescryer** [comment]
Are you on a version of NPM below v3?  Peer Dependencies are now optional, with a CLI warning only.

Canvas has its own dependencies/requirements which make it impossible to link to as a straight dependency. 

Canvas is only a hard dependency if you wish to use Resemble.js in NodeJS.

I need to think about this a little, I'm happy to change the versions just not sure on the implications.

**Comment by jamescryer** [comment]
I'm hoping this is resolved now that Resemble has dropped the peer dependency and added a straight dependency on canvas-prebuilt.
