### ISSUE TITLE
Segmentation fault caused by onComplete()

### ISSUE THREAD

**Issue by ruxiang05** [Huddle/Resemble.js#111]
`baseImage = fs.readFileSync('${process.cwd()}/test/baseImages/Example-with-text.png');
  diffImage = fs.readFile('${process.cwd()}/test/baseImages/Example-with-text.diff.png');
  resemble(baseImage).compareTo(diffImage);`

If I chain onComplete() after compareTo it gives me a segmentation fault. I'm not doing anything different than your examples, how is this possible? Using Node 8.0.0

**Comment by jamescryer** [comment]
Nothing obvious to me.  Have you tried using the CompareImages helper function? https://github.com/Huddle/Resemble.js#usage Does that approach work?

**Comment by ruxiang05** [comment]
I have used something else
