### ISSUE TITLE
Use canvas prebuilt

### ISSUE THREAD

**Issue by LarsDenBakker** [Huddle/Resemble.js#114]
I want to add resemblejs to the test tooling of my company's projects, but the dependency on canvas is blocking me currently. I cannot add it, and expect all devs to go through the pain of installing canvas manually. Especially in windows. And for all our jenkins jobs it will be a problem as well.

Recently canvas started providing prebuilt packages: https://github.com/node-gfx/node-canvas-prebuilt

Please consider using that instead, or offering it as an alternative.

See an example of the required change here: https://github.com/gidztech/Resemble.js/commit/c2068b96abc1ff01a2222bbea59671df4c1f5ff1

**Comment by jamescryer** [comment]
That's done now.  Thanks for your feedback.

**Comment by LarsDenBakker** [comment]
Thanks a lot!
