### ISSUE TITLE
Resemble assumes a PNG when passing a buffer

### ISSUE THREAD

**Issue by PomegranateApps** [Huddle/Resemble.js#115]
I'm passing image data as a buffer in JPG format but Resemble assumes a PNG in the `loadImageData` function when passing data as a buffer.

**Comment by jamescryer** [comment]
What's the affect of this?  The tests are passing for with JPG buffers https://github.com/Huddle/Resemble.js/blob/master/nodejs-tests/resemble.test.js#L73

**Comment by PomegranateApps** [comment]
Yes, files are fine but if I pass a buffer it would fail. I reading the contents of a remote url into a buffer and then sending to Resemble. Here is the code for that function.
```

		function loadImageData( fileData, callback ){

			if (Buffer.isBuffer(fileData)) {
                                // Issue is here
				var png = new PNG();
				png.parse(fileData, function (err, data) {
				  callback(data, data.width, data.height);
				});
			} else {
				var ext = fileData.substring(fileData.lastIndexOf(".")+1);
				if(ext=="png") {
					var png = new PNG();
					fs.createReadStream(fileData)
					  .pipe(png)
					  .on('parsed', function() {
						callback(this, this.width, this.height);
					  });
				}
				if(ext=="jpg" || ext=="jpeg") {
					var jpegData = fs.readFileSync(fileData);
					fileData = jpeg.decode(jpegData, true);
					callback(fileData, fileData.width, fileData.height);
				}
			};
		}
```

**Comment by jamescryer** [comment]
I believe you are referring to https://github.com/lksv/node-resemble.js/blob/master/resemble.js#L115.

This is a different project (See this projects implementation https://github.com/Huddle/Resemble.js/blob/master/resemble.js#L199 )
