### ISSUE TITLE
Segementation fault

### ISSUE THREAD

**Issue by JakeGinnivan** [Huddle/Resemble.js#120]
Hi,

I have just hit the same issue as #111 which seems to be caused by the images themselves maybe. I am using the same code and a buffer image taken from puppeteer (https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagescreenshotoptions) without issues.

But my tests here https://github.com/JakeGinnivan/jest-image-snapshot/blob/master/tests/jest-image-snapshots.spec.ts cause a segmentation fault (specifically `Command failed with signal "SIGSEGV"`).

Any ideas on where to look?

**Comment by jamescryer** [comment]
I am unable to repro this issue.  I'll leave the ticket open for now in the hope that someone else may be able to help.

**Comment by JakeGinnivan** [comment]
I am ok with this being closed so cleanup open issues. I have ended up using a native image comparison library.
