### ISSUE TITLE
Using without npm

### ISSUE THREAD

**Issue by stndlkr200** [Huddle/Resemble.js#33]
How to use resemble.js without npm ?

<script src="http://huddle.github.io/Resemble.js/resemble.js"></script>

var timer=setInterval(function(){
resemble(ak).compareTo(whiteimg).onComplete(function(){
console.log(data);
},2000);

This giving Error in Console: Uncaught SyntaxError: Unexpected end of input   (index:1)

**Comment by jamescryer** [comment]
You've got a syntax error.  Try closing the onComplete callback with `})`
