### ISSUE TITLE
Image scale to same size before comparison

### ISSUE THREAD

**Issue by timkarnold** [Huddle/Resemble.js#36]
When comparing two images from the same source but were saved with different dimensions such as a thumbnail, Resemble.js reports that they are not similar as the pixel data comparison only occurs in the overlap of the photos starting from the top left corner.

**Example 1: Thumbnail (50x50) vs Source (282x281)** *Note the thumbnail overlaid on top left of the larger image, failing comparison*
![screen shot 2015-02-18 at 9 37 46 am](https://cloud.githubusercontent.com/assets/1531526/6248997/1fc47ebc-b752-11e4-9733-dccf28e21ee4.png)

Desired behavior is to scale the images to be the same size before comparing pixel data (still reporting that the input images have different resolutions). For demonstration purposes, I resized the source image in Photoshop to match 50x50 of the thumbnail and re-ran the comparison, which reported much more accurate results.

**Example 2:** Thumbnail (50x50) vs Scaled Source (50x50)** *Much more accurate comparison results.*
![screen shot 2015-02-18 at 9 37 58 am](https://cloud.githubusercontent.com/assets/1531526/6249042/7fc06efc-b752-11e4-8082-452e83e91376.png)

I am experimenting with resizing the images with Canvas elements before loading into Resemble.js, but I believe this is an issue worth considering in the library core.

**Comment by jamescryer** [comment]
It's a good feature suggestion, I'll accept a PR.

**Comment by masi** [comment]
@timkarnold In your example you downscaled the larger image. Did you also experiment with upscaling the smaller image? If so, what have been the results?

**Comment by steel** [comment]
Looking forward to this as I have images that are produced on a retina display at 2x resolution and being compared to images taken on non-retina at 1x. Built in downscaling the 2x one would be awesome!

**Comment by c301** [comment]
@jamescryer please review PR with feature https://github.com/Huddle/Resemble.js/pull/60

**Comment by jamescryer** [comment]
I believe that PR #60 resolved this ticket.. Closing.
