### ISSUE TITLE
GitHub Pages demo not working

### ISSUE THREAD

**Issue by KevOrr** [Huddle/Resemble.js#38]
Hey there, this seems like a really cool project, so I wanted to try out the demo.
Unfortunately, when I try to drop [this image][1] into any of the three dropzones, I get `Uncaught TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.` in the Chrome developer console.
It seems the offending line is [34 of demoassets/main.js][2].

I should say that I'm using Chrome 41.0.2272.101 m

EDIT: So it seems, after capturing the `ondrop` event, that the `dataTransfer` shows no files:

    > temp1.originalEvent.dataTransfer
    < DataTransfer {items: DataTransferItemList, files: FileList, types: Array[0], effectAllowed: "all", dropEffect: "none"…}
        dropEffect: "none"
        effectAllowed: "all"
        files: FileList
          length: 0
          __proto__: FileList
        items: DataTransferItemList
          length: 0
          __proto__: DataTransferItemList
        types: Array[0]
          length: 0
          __proto__: Array[0]
        __proto__: DataTransfer

Not sure why that would be, but hope that helps.

[1]: http://i.imgur.com/NUb5TcJ.png
[2]: https://github.com/Huddle/Resemble.js/blob/gh-pages/demoassets/main.js#L34

**Comment by jamescryer** [comment]
Hi.  I'm not seeing an issue, so I wonder if it is because of local security settings or a browser plugin.  Please let us know if you find out.
