### ISSUE TITLE
Wrong work compared with cached image

### ISSUE THREAD

**Issue by mynoheart** [Huddle/Resemble.js#39]
If one of images caching, then callback ```hiddenImage.onload``` called twice.
The reason this behavior next lines (started at 163 line)
``` javascript
  if (hiddenImage.complete) {
    hiddenImage.onload();
  }
````
If this lines remove, then all work correctly.
Thanks.

**Comment by mynoheart** [comment]
Problem repeated in Chrome and Firefox.

**Comment by jamescryer** [comment]
Thanks for ticket.

Looks like those lines were added deliberately, which makes me think removing them would introduce another bug.
 
https://github.com/Huddle/Resemble.js/commit/b6fe577f6ba881dd3534a2bd31ad0a045927a9ff

I'm going to let this issue sit for a while to see if anyone else has this problem.

**Comment by mynoheart** [comment]
Thes lines added with comment "Call hiddenImage.onload if image is cached", but if images is cached, then onload called without manual call.
