### ISSUE TITLE
Show difference intensity?

### ISSUE THREAD

**Issue by jamescryer** [Huddle/Resemble.js#4]
Would it be possible to show the differences between the two images by shading the pink pixels with varying color intensities, which represent how far away the colors on the 2 images are?

**Comment by masi** [comment]
Perhaps if you transform the RGB values to a hue value (either HSL or HSV). This will tell you the difference in terms of the HSL/HSV colour wheel.

If you want you could also take saturation and/or luminance/value into account to get a 2D or 3D vector for measuring the distance.

@kamilbielawski Is this what you have implemented?

**Comment by kamilbielawski** [comment]
@masi my implementation calculates difference between two colors as a sum of differences between each of the RGB components.
I like your ideas, though. Feel free to update my code (or add new methods).

**Comment by masi** [comment]
This is what CSS offers:

http://www.w3.org/TR/css3-color/#hsl-color
http://dev.w3.org/csswg/css-color-4/#the-hwb-notation

Background information:

http://en.wikipedia.org/wiki/RGB_color_model
http://en.wikipedia.org/wiki/HSL_and_HSV
http://en.wikipedia.org/wiki/HWB_color_model
http://en.wikipedia.org/wiki/Lab_color_space
http://en.wikipedia.org/wiki/CIELUV
http://en.wikipedia.org/wiki/Color_difference

Practical infos and implementations:

http://www.compuphase.com/cmetric.htm
http://stevehanov.ca/blog/index.php?id=116
http://www.emanueleferonato.com/2009/08/28/color-differences-algorithm/

Conclusion:

Pick to choose between how easy to implement, how fast to compute or how near it comes to human perception.

Cheers,
Masi
