### ISSUE TITLE
Image is not defined

### ISSUE THREAD

**Issue by iam404** [Huddle/Resemble.js#41]
hii guys..
I was using your project with NightwatchJS for screenshot comparison for automated testing.
There seems to an issue i am getting every time  "Image is not defined"

![selection_192](https://cloud.githubusercontent.com/assets/11330522/7385946/71469e5a-ee6b-11e4-9381-fdde94724142.jpg)

Any help will be highly appreciated
Thanks in advance

**Comment by Droogans** [comment]
You have to have Cairo installed for image comparison in node. I've looked for one-off solutions written in pure javascript and it looks like they don't exist.

If you try to install Cairo on Mac, take a look at https://github.com/Homebrew/homebrew/issues/14123#issuecomment-26211017 in case you get some pathing issues from brew.

For using resemble in node, see https://github.com/kpdecker/node-resemble.

**Comment by jamescryer** [comment]
ResembleJS is for "In-browser" image comparison, but that's not to say it can't be tweaked for NodeJS.  https://github.com/kpdecker/node-resemble Looks like it might be a good solution for your needs.

Let us know if you get something working.

**Comment by iam404** [comment]
@jamescryer  @Droogans 
Thanks for the link and informations.
node-resemble seems to be working fine .

Though not an issue But i need to eliminate some dynamic elements from comparison .Is it possible in resemble js to eliminate dynamic parts that changes often from baseline image .
like: https://github.com/webdriverio/webdrivercss

**Comment by jamescryer** [comment]
Resemble just does image comparison.   Presumably you need to use NightwatchJS functionality to hide the dynamic UI before taking the screenshot for comparison.

**Comment by Droogans** [comment]
That's not necessarily true. @iam404 I'm working on a library that uses Protractor and Mocha that will be able to support that soon. https://github.com/rackerlabs/snappit-mocha-protractor

Depending on your tooling, you may be able to use it. Admittedly, it's a fairly specific toolset to solve a pretty specific problem for myself. If you can't use it, at least you'll have source code that you can use for your own project.

https://github.com/rackerlabs/snappit-mocha-protractor
