### ISSUE TITLE
Regex doesn't consider port

### ISSUE THREAD

**Issue by Itrulia** [Huddle/Resemble.js#42]
So my web app does pull the images from a service. Now since I also develop the service I have both local.

So when my web app on `localhost:3000` tries to fetch images from `localhost:8888` it fails, because the crossorigin isn't set.

Lines that causes this:

* [Regex](https://github.com/Huddle/Resemble.js/blob/master/resemble.js#L64)
* [Cross origin](https://github.com/Huddle/Resemble.js/blob/master/resemble.js#L139)

Why not always set the `crossorigin` to `anonymous`?

**Comment by jamescryer** [comment]
https://github.com/Huddle/Resemble.js/commit/e6dab9aaf06415bd62cadb5d72a09bcc37b56128
