### ISSUE TITLE
Compare two images created at runtime using Resemble.js

### ISSUE THREAD

**Issue by rachits123** [Huddle/Resemble.js#45]
Hello sir!!

I am unable to compare two image files generated during runtime and stored  as variables e.g.(var a, var b)  using Resemble.js

I am trying to do this in a single javascript file 

Please help!!

**Comment by jamescryer** [comment]
I can't think of a reason why this wouldn't work. So long as var a and b are valid file blobs with the correct image mime type. Please let us know if you get it to work, would be great to see a code example as well.
