### ISSUE TITLE
Subtle changes in images are reported as still being 100% identical

### ISSUE THREAD

**Issue by TheJaredWilcurt** [Huddle/Resemble.js#46]
## Explanation of issue

If I compare a 100x100px solid white (`#FFFFFF`) image to a 100x100px image that is pure `#FAFAFA`, despite being able to visually see a difference in these two files, Resemble still thinks there is no difference between them.

Is there a way to max out Resemble's accuracy? So that even if I just change a single pixel from `#FFFFFF` to `#FEFFFF` it would result in a mismatch/fail?

I just need to know if two images are literally pixel-for-pixel identical. I'm working with lossless png compression algorithms and need to verify that the compressed images they produce truly are lossless.

If you know of a better tool for this that can be ran with node (so I can automate my testing process), that would be helpful as well.

* * *

## Details on my test

**The example images I used:**

0.png | 1.png
:--|:--
![0](https://cloud.githubusercontent.com/assets/4629794/8985282/769b540a-36a4-11e5-967b-cdde0a4de1f6.png) | ![1](https://cloud.githubusercontent.com/assets/4629794/8985280/709f79c8-36a4-11e5-8c84-ebf4be9a36f0.png)

**My code:**

    var resemble = require("node-resemble-js");
    
    var fileA = "0.png";
    var fileB = "1.png";
    
    var diff = resemble(fileA).compareTo(fileB).ignoreNothing().onComplete(function(data){
        console.log(data);
    });

**Which when ran returns:**

    { isSameDimensions: true,
      dimensionDifference: { width: 0, height: 0 },
      misMatchPercentage: '0.00',
      analysisTime: 15,
      getDiffImage: [Function] }

* * *

## Playing with the source code

In `resemble.js` I changed the following line:

    data.misMatchPercentage = (mismatchCount / (height*width) * 100).toFixed(2);

to:

    data.numberOfDifferingPixels = mismatchCount;
    data.totalNumberOfPixels = height * width;
    data.misMatchPercentage = (mismatchCount / (height*width) * 100).toFixed(2);

but `numberOfDifferingPixels` just returns 0. So obviously there is something either wrong with the settings I'm using, or with the logic that Resemble is currently using.

If I change the `isColorSimilar` function to:

    function isColorSimilar(a, b, color){
        if(a === b){
            return true;
        } else {
            return false;
        }
    }

it seems to work correctly. Perhaps pass in a boolean value for "highAccuracy" that, if true, runs the code above, like:

    function isColorSimilar(a, b, color, accuracy) {

        if ( typeof a === 'undefined' || typeof b === 'undefined' ) {
            return false;
        }

        var absDiff = Math.abs(a - b);

        if ( accuracy && (a === b) ) {
            return true;
        } else if ( accuracy ) {
            return false;
        } else if ( (a === b) || (absDiff < tolerance[color]) ) {
            return true;
        } else {
            return false;
        }
    }

Then users can just do:

    var diff = resemble(fileA).compareTo(fileB).ignoreNothing().highAccuracy().onComplete(function(data){
        console.log(data);
    });

That's how I'd do it anyway. However that would make the "ingoreNothing" misleading.

**Comment by jamescryer** [comment]
Does this change fix your issue? https://github.com/Huddle/Resemble.js/pull/44 

Also, I notice in your code sample that you are using https://github.com/lksv/node-resemble.js, you'll need to raise a ticket on that repo as well.

**Comment by MondeSameWave** [comment]
I have the same issue

**Comment by brunano21** [comment]
I have the same issue.

**Comment by jamescryer** [comment]
the `ignoreNothing` method is now more sensitive, with and 'ignoreLess' method being the equivalent of the old `ignoreNothing`
