### ISSUE TITLE
diff bounding box?

### ISSUE THREAD

**Issue by RobertSmart** [Huddle/Resemble.js#49]
Hi,

Is it possible to get the bounding box in pixel units of the areas of the image that have changed?

Thanks,

**Comment by jamescryer** [comment]
Sorry for the late reply.  The data received with the onComplete callback contains a property called diffBounds.

```javascript
resemble(file).compareTo(file2).onComplete(function(data){
  console.log(data.diffBounds); // {bottom: 0, left: 0, right: 0, top: 0}
});
```
