### ISSUE TITLE
diff with original image pixels instead of solid colour??

### ISSUE THREAD

**Issue by RobertSmart** [Huddle/Resemble.js#51]
Hi, 

Is there anyway I can get resemble to output the dif using the pixel colours from one of the original source images?

I'm developing a camera streaming site, and rather than send a whole frame of the camera on each cycle, I figured it might be more efficient to just send the differences to the last frame. So if I could get the difference between image A and image B, with the pixels matching image B (kind of like using the dif as a mask over image B), and the rest transparent, then by sending that smaller dif over the wire I can merge it with image A on the server and get a very close approximation of the true image B frame.  

Does sound feasible?

Thanks

**Comment by Lucas-naceri** [comment]
We got aproblem .

**Comment by RobertSmart** [comment]
???? Strange comment.

I've actually just started to look at this myself, so will probably figure it out soon enough.

**Comment by RobertSmart** [comment]
Turns out this was remarkably easy, which is a testament to the quality of the existing code. I simply added another errorPixelTransform like this:

		original : function(d1,d2){
			return {
				r: d2.r,
				g: d2.g,
				b: d2.b,
				a: d2.a
			}	
		},

now instead of return the supplied errorpixel colour, it return the actual pixel colour value from the second 'compared to' image. The result is quite interesting actually!
