### ISSUE TITLE
Transparent grid pattern on diff image when comparing large images with antialiasing ignored

### ISSUE THREAD

**Issue by nikrolls** [Huddle/Resemble.js#52]
To reproduce:

1. Go to http://huddle.github.io/Resemble.js/
2. In the Compare Two Images section, upload two large screenshots (at least 1200x1200 or more, eg http://i.imgur.com/f4Zy09J.jpg & http://i.imgur.com/kvOUgOI.jpg). Note that the diff image is as expected.
3. Switch to 'Ignore Antialiasing'; note that the diff image has a cross-hatch pattern.

Reading through the source, it seems like this is to do with `largeImageThreshold` and skipping every 6th pixel for large images when `ignoreAntialiasing` is true. What is the purpose of this skipping – is it a performance optimisation? I would think it would only save approximately 1/4 of the processing time. Can an option be added to disable it, or even better have it off by default and allow it to be enabled by the user when they want this optimisation?

Edit: updated with more accurate information after reading the source code

**Comment by jamescryer** [comment]
It's mentioned on the README

"By default, the comparison algorithm skips pixels when the image width or height is larger than 1200 pixels. This is there to mitigate performance issues.

You can switch this modify this behaviour by setting the largeImageThreshold option to a different value. Set it to 0 to switch it off completely."

**Comment by nikrolls** [comment]
Ugh, so sorry. We're using node-resemble and so I clearly didn't read your own readme correctly. Thanks for that, we'll use the option you mentioned.
