### ISSUE TITLE
Compare multiple images from ftp server

### ISSUE THREAD

**Issue by etrust** [Huddle/Resemble.js#56]
Hi,

it's possible to compare multiple images on the background? I want that the user upload one image that will be compared with 1'000 images on a ftp server and show the image with the less difference.

Can this be done with resemble.js ?

Thanks!

**Comment by jamescryer** [comment]
You'll have to write your own code to loop through each image to compare with user's image, and keep track of each comparison result so you know which comparison show the least difference.

This is not something Resemble could do itself.
