### ISSUE TITLE
Very slow performance with hundreds of images

### ISSUE THREAD

**Issue by paul321** [Huddle/Resemble.js#57]
Hi

We are trying to compare 900 image one with each other to see how many duplicates we have in our app, we are using Electron and the performance of Resemble it's not good at all, the interface freezes for 4-5 seconds when we compare a lot of images using Promises and async to loop over. Images compared are 170x170 pixels, files are stored locally on hdd and the url starts with file:///c:... so the network latency doesn't exists

here is a screenshot from Dev Tools, you will see that the function onload takes a lot of time just for 1 image:
![untitled-1](https://cloud.githubusercontent.com/assets/555502/13029583/f88a9044-d298-11e5-9981-93876fc36f09.jpg)

**Comment by jamescryer** [comment]
Resemble will never be as performant as a server-side alternative, for your case I would look at other tools.

I'm pretty sure Resemble could be more optimised, and would appreciate any suggestions and PRs that would help with performance.
