### ISSUE TITLE
Feature Request: Output Diff Portion From Inputs

### ISSUE THREAD

**Issue by skiplist** [Huddle/Resemble.js#62]
If we are comparing image A to image B, it would be nice to save A-B or B-A to a file.  This would provide the "difference" between the images as a piece of one of the original two images (As opposed to just highlighting, which obscures what is "under" the highlight)

**Comment by jamescryer** [comment]
I think having the option to show only the difference in un-highlighted form is a good feature request.  I don't think Resemble needs to produce two images though - it would be easy for a custom implementation to invoke Resemble with both A->B and B<-A comparisons
