### ISSUE TITLE
Percent of difference

### ISSUE THREAD

**Issue by devdept** [Huddle/Resemble.js#64]
We compare mostly images of 3D objects on white background. The image size is always the same (1024x768). Depending on the object size (a ball vs a pencil) the percent of difference does not reflect the reality. Would it be possible to add an option to skip white (or the specified flat background color) from the percent of difference value?

Thanks.

**Comment by jamescryer** [comment]
I don't quite understand your use-case.  But I'm always open to feature requests and happy to review/accept PRs if they solve a clear problem.  

Can you share a couple of images to better describe your problem?

**Comment by devdept** [comment]
Hi James,

Here are sample images (attached). We would like to compute the difference ignoring white background -huge- number of pixels. In this way the percent of error represent the actual error between the two shapes.

[image_comp.zip](https://github.com/Huddle/Resemble.js/files/236600/image_comp.zip)

**Comment by jamescryer** [comment]
Thanks. So these two images show a 0.56% percent difference with "ignore anti-aliasing" enabled.  Are you saying that this is result is incorrect?

**Comment by devdept** [comment]
I am saying that I cannot probably compare 0.56% with 0.17% of this second case... If you could ignore white background pixels the percent values would be different and close to what we are after.

[image_comp2.zip](https://github.com/Huddle/Resemble.js/files/236623/image_comp2.zip)

**Comment by jamescryer** [comment]
So, what is the actual result you expect for each case? Do you expect Resemble.js to return a no-difference result?

If so, you could try increasing the tolerance levels, by adding on a new method https://github.com/Huddle/Resemble.js/blob/master/resemble.js#L640

I'm happy to review/accept a PR for your requirement.

**Comment by devdept** [comment]
No, only a percent of difference that doesn't take in account the white background. What do you mean exactly with 'PR'?

**Comment by jamescryer** [comment]
Sorry, Github terminology.  PR means Pull Request.  If you would like to submit a Pull Request with your feature, with clear test data and expected results, then I'll be happy to review.
