### ISSUE TITLE
Help Request

### ISSUE THREAD

**Issue by Robbottone** [Huddle/Resemble.js#68]
Hi
I know maybe I'm asking too much, but is it possible to have a "help" commented resemble.js file? Something that would clarify the main activities of the code, i know that is a really hardworking request, but i'm new in the image comparison and this could help me a lot! 

I need this library to automate some test cases that I would run on a software.

Thank you anyway!

**Comment by jamescryer** [comment]
Sorry, it's outside the scope of this project to add CLI compatibility and help.  You would need a wrapper library, perhaps written in NodeJS.
