### ISSUE TITLE
Cannot get .scaleToSameSize() to work

### ISSUE THREAD

**Issue by eric314** [Huddle/Resemble.js#71]
Wrestling with this method and can't seem to get it.

Here's my work:

```

resemble
        .resemble(baselinePath)
        .compareTo(resultPath)
        .ignoreAntialiasing()
// Uncommenting this causes failure. Commenting it out works:      .scaleToSameSize()
        .onComplete(callback);
```

**Comment by jamescryer** [comment]
I can't repro a bug. What are the values of `baselinePath` and `resultPath`?

**Comment by optikalefx** [comment]
I've got the same problem

this works

```
resemble(file1).compareTo(file2).ignoreAntialiasing().onComplete((data) => {
```

This doesn't

```
resemble(file1).compareTo(file2).ignoreAntialiasing().scaleToSameSize().onComplete((data) => {`
```

My file1 is a buffer from `http://ecx.images-amazon.com/images/I/41u-NKBu7IL.jpg`
and file 2 is a buffer from `https://i.embed.ly/1/image/resize?url=https://cl.ly/172x3T3Z0t1B/resize%20(1).jpeg&key=a86a4963aba54ee198641970e73b9756&width=1500`

The buffer part, and embed.ly part are not the issue as it works without the scaleToSameSize(). But without that, i'm getting wildly incorrect compares.

**Comment by optikalefx** [comment]
Mine is using the node-canvas version by the way.

**Comment by greghesp** [comment]
I get the same issue here too:
Caught TypeError: resemble(...).compareTo(...).ignoreColors(...).scaleToSameSize is not a function

					`resemble('lotsoftext.jpg').compareTo('test.jpg').ignoreColors().scaleToSameSize().onComplete(function(data){`

**Comment by optikalefx** [comment]
Yea any ideas how to get scaleToSameSize() to work?

**Comment by jamescryer** [comment]
Checked this again, still no repro. Suspect that the problem is with one of the NodeJS ports
