### ISSUE TITLE
Wrong RGB values for white pixels

### ISSUE THREAD

**Issue by ilCosmico** [Huddle/Resemble.js#72]
Hi @jamescryer ,

The ImageData of the attached "full-white" bitmap gives all the pixels with RGB values equal to 254 instead of 255

![image](https://cloud.githubusercontent.com/assets/8678145/16583566/afb2f4c2-42b6-11e6-98c2-b02fef8fe864.png)

Any ideas?

[TestWhite.zip](https://github.com/Huddle/Resemble.js/files/347664/TestWhite.zip)

**Comment by jamescryer** [comment]
Could be anything from OS, browser to the Image editor you used. But the problem is unlikely to be caused by the JS library.

**Comment by ilCosmico** [comment]
It sounds strange to me too, but I tried to read the image in C# and it gets 255...I tried to open it with Paint in Windows and still it gets 255... only with JS it seems to get 254.
