### ISSUE TITLE
Progress of comparing two images

### ISSUE THREAD

**Issue by preeti07** [Huddle/Resemble.js#75]
in my project, I have to show a progress bar, while it's comparing. Ids it possible to have return some progress data / timer how much time it will take to compare my two images, please. Or any idea I can implement it on my side keeping resemble library as it is? Thanks.

**Comment by jamescryer** [comment]
Sorry, that's it's not possible to show a progress bar.

**Comment by preeti07** [comment]
Thanks for letting know. I will put just a loader rather than progress bar. :)
