### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by peerapixs** [Huddle/Resemble.js#78]
**Hi All,**

I tried to configure the option and without user interface (remove buttons), But it isn't work.
I just need the fix images path in code and need to see the result of  diff images.

		var ignoreAntialiasing = true;
		var ignoreColors = false;
		var scaleToSameSize = true;

PS. Nomally I use PHP.

**Comment by jamescryer** [comment]
With the Resemble.js API you would achieve this by chaining the appropriate methods.  See below.

```javascript
var diff = resemble(file).compareTo(file2).ignoreAntialiasing().scaleToSameSize().onComplete(function(data){
    console.log(data);
});
```
