### ISSUE TITLE
Drag images from another Browser window or Tab.

### ISSUE THREAD

**Issue by rayerhak** [Huddle/Resemble.js#80]
Hi,

it doesn't work when you drag an image from another tab or window.
is there anyway to make it work on both the analysis and comparison.
I hope there will be a way , i really need this function and i like your script.

Best regards.

**Comment by jamescryer** [comment]
I think that's possible, Paste event maybe.  It's not core to the library itself, but I'm happy to review a Pull Request on the demo page code
