### ISSUE TITLE
Error instantiating the Image object

### ISSUE THREAD

**Issue by pedgarcia** [Huddle/Resemble.js#81]
When I call the function to compare two images I am getting the following error:
```
Unhandled rejection ReferenceError: Image is not defined
    at loadImageData (/Users/pgarcia/work/github/qa/dispatcher-ui/lib/imagediff/node_modules/resemblejs/resemble.js:150:26)
```

I can't find the Image object and where is it declared?

I wonder what I am missing here?

Thanks

Paulo

**Comment by jorge-sanz** [comment]
Same problem here!

**Comment by jorge-sanz** [comment]
@jamescryer

**Comment by jamescryer** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image

`Image` is only available in the browser; this library is only designed to work in a browser.
