### ISSUE TITLE
node version

### ISSUE THREAD

**Issue by peter-mouland** [Huddle/Resemble.js#84]
I understand you are currently recommending an external library for nodeJS users. 

Unfortunately, that recommended library is no longer supported and requests for maintainers doesn't seem to have got very far: https://github.com/kpdecker/node-resemble/issues/11

Is it possible to bring in the node version into this app?  Would a PR, perhaps inside a `/bin` (or where ever feels right to you), be accepted?

**Comment by peter-mouland** [comment]
apologies - the referenced repo above is not the repo you recommend (confusing package names to blame i reckon)!

however,  the recommended node version is someway out of date.  I've submitted a PR to update their dependencies.  I hope it gets accepted, but i think the above question is still valid.

**Comment by jamescryer** [comment]
There's no value for me or Huddle in maintaining a NodeJS port, but of course I welcome other people using and adapting Resemble for their own needs, ideally keeping that contribution open-source.

Thanks

**Comment by graingert** [comment]
See also https://github.com/lksv/node-resemble.js/issues/21

**Comment by graingert** [comment]
@jamescryer can you re-open this now that resemble has a node port?
