### ISSUE TITLE
unexplained diff when produced locally

### ISSUE THREAD

**Issue by hstorc** [Huddle/Resemble.js#93]
Hello,
You got an amazing tool, well done!!
That said, I got couple of diff results that I cannot explain. Attached is prod-short and stage-shot to compare, and results as the result.
When I drag and drop on your website it works great with minimal differences.
When I use gm script the results make sense as well.
But when I use webdrivercss that implements your code, or call directly to your module,
I get the attached weird results.
Your advise appreciated
![prod-shot](https://cloud.githubusercontent.com/assets/10091490/23193466/2b664846-f877-11e6-8693-6b3c260ac0da.png)
![stage-shot](https://cloud.githubusercontent.com/assets/10091490/23193465/2b6552ec-f877-11e6-9a73-aa3765ec3baa.png)
![results](https://cloud.githubusercontent.com/assets/10091490/23193477/3889446a-f877-11e6-8804-4c69088393c5.png)

,
Hayim

**Comment by wswebcreation** [comment]
Hi @hstorc,

The comparison result looks like diff in the size. If you check the dimensions you see that it is comparing 1366x7408 to 1386x7452. Looks like the site can handle the "scaleToSameSize" but the webdrivercss you are mentioning to is not.

**Comment by jamescryer** [comment]
The difference in size is the likely cause.  Please raise an issue against the WebdriverCSS project.
